version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    networks:
      - docker-local
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"

  db:
    image: postgres:latest
    container_name: PostgresCont
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_database
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: my_user

    ports:
      - "5432:5432"
    networks:
      - docker-local
volumes:
  postgres_db:
    driver: local
networks:
  docker-local:
    name: docker-local